FROM trophime/magnettools:bookworm-poetry
#FROM trophime/magnettools:bullseye-poetry

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 DEBIAN_FRONTEND=noninteractive
RUN echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections

USER root
RUN apt-get update \
    && apt-get install -y iputils-ping vim-nox emacs-nox \
    && apt-get install -y wait-for-it \
    && apt-get install -y debconf-utils
    
USER feelpp

