version: '3'
services:
  proxy:
    image: traefik:v2.9
    command: --api.insecure=true --providers.docker --providers.docker.exposedbydefault=false --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik/:ro
      - ./certs:/etc/ssl/traefik/:ro
  web-api:
    build: .
    command: poetry run uvicorn python_magnetdb.web:app --host 0.0.0.0 --port 8000
    working_dir: /home/feelpp/test
    volumes:
      - .:/home/feelpp/test
      - ./poetry-cache:/home/feelpp/.cache/pypoetry
      - ../data/:/data:ro
      - ../images:/images:ro
    links:
      - redis
      - postgres
      - minio
      - lemonldap
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.magnetdb.local`)"
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
    environment:
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET: magnetdb
      REDIS_ADDR: redis://redis:6379/0
      DATABASE_HOST: postgres
      IMAGES_DIR: /images
      SECURITY_AUTHORIZATION_SERVER: http://lemonldap
      FRONT_SECURITY_AUTHORIZATION_SERVER: https://auth.lemon.magnetdb.local
      FRONT_SECURITY_AUTHORIZATION_HOST_SERVER: auth.lemon.magnetdb.local
  web-worker:
    build: .
    privileged: true
    command: poetry run celery -A python_magnetdb.worker worker --loglevel=info
    working_dir: /home/feelpp/test
    volumes:
      - .:/home/feelpp/test
      - ./poetry-cache:/home/feelpp/.cache/pypoetry
      - ../data/:/data
      - ../images:/images
    links:
      - redis
      - postgres
      - minio
    environment:
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET: magnetdb
      REDIS_ADDR: redis://redis:6379/0
      DATABASE_HOST: postgres
      IMAGES_DIR: /images
  web-app:
    # image: node:16
    build:
      context: web
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        API_ENDPOINT: "https://api.magnetdb.local"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`magnetdb.local`)"
      - "traefik.http.routers.app.entrypoints=https"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.services.app.loadbalancer.server.port=80"
  lemonldap:
    image: tiredofit/lemonldap:2.0.24
    environment:
      LOGLEVEL: debug
      LETSENCRYPT_HOST: auth.lemon.magnetdb.local manager.lemon.magnetdb.local handler.lemon.magnetdb.local api.lemon.magnetdb.local
      VIRTUAL_HOST: auth.lemon.magnetdb.local manager.lemon.magnetdb.local handler.lemon.magnetdb.local api.lemon.magnetdb.local
      VIRTUAL_PROTO: https
      VIRTUAL_PORT: 80
      DOMAIN_NAME: lemon.magnetdb.local
      API_HOSTNAME: api.lemon.magnetdb.local
      MANAGER_HOSTNAME: manager.lemon.magnetdb.local
      PORTAL_HOSTNAME: auth.lemon.magnetdb.local
      HANDLER_HOSTNAME: handler.lemon.magnetdb.local
      TIMEZONE: Europe/Paris
    volumes:
      - lemonldap:/var/lib/lemonldap-ng
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lemon.rule=Host(`auth.lemon.magnetdb.local`) || Host(`manager.lemon.magnetdb.local`) || Host(`handler.lemon.magnetdb.local`) || Host(`api.lemon.magnetdb.local`)"
      - "traefik.http.routers.lemon.entrypoints=https"
      - "traefik.http.routers.lemon.tls=true"
      # - "traefik.http.services.lemon.loadbalancer.server.port=80"
  redis:
    image: redis
    ports:
      - 6379:6379
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    # user: "${UUID}:${GID}"
    environment:
      POSTGRES_USER: magnetdb
      POSTGRES_PASSWORD: magnetdb
      TZ: 'Europe/Paris'
      PGTZ: 'Europe/Paris'
    volumes:
      - postgres:/var/lib/postgresql/data
  minio:
    image: minio/minio
    command: server /data --console-address ":9080"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - 9000:9000
      - 9080:9080
    volumes:
      - minio:/data
  pgadmin:
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@magnetdb.fr'
      PGADMIN_DEFAULT_PASSWORD: 'password'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.magnetdb.local`)"
      - "traefik.http.routers.pgadmin.entrypoints=https"
      - "traefik.http.routers.pgadmin.tls=true"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
    volumes:
      - pgadmin:/pgadmin
    links:
      - postgres
volumes:
  minio: {}
  postgres: {}
  lemonldap: {}
  pgadmin: {}
