version: '3.3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: magnetdb-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./network_internal.conf:/etc/nginx/network_internal.conf
    environment:
    - NETWORK_ACCESS=internal

  lemonldap-app:
    # image: tiredofit/lemonldap:latest
    image: tiredofit/lemonldap:2.0.24
    container_name: lemonldap-app
    volumes:
    - ../magnetdb-data/lemonldap-ng-data/conf:/var/lib/lemonldap-ng/conf
    - ../magnetdb-data/logs:/www/logs
    #- ./assets/custom:/assets/custom
    environment:
    - VIRTUAL_HOST=sso.lncmig.local,manager.sso.lncmig.local,handler.sso.lncmig.local
    # - VIRTUAL_PROTO=https
    - VIRTUAL_PORT=80
    - NETWORK_ACCESS=internal
    # - LETSENCRYPT_HOST=sso.lncmig.local,manager.sso.lncmig.local,handler.sso.lncmig.local
    # - LETSENCRYPT_EMAIL=christophe.trophime@lncmi.cnrs.fr

    - CONTAINER_NAME=lemonldap-app

    - DOMAIN_NAME=lncmig.local
    - API_HOSTNAME=api.manager.sso.lncmig.local
    - MANAGER_HOSTNAME=manager.sso.lncmig.local
    - PORTAL_HOSTNAME=sso.lncmig.local
    - HANDLER_HOSTNAME=handler.sso.lncmig.local
    - LOG_LEVEL=debug
    - TIMEZONE='Europe/Paris'
    depends_on:
      - nginx-proxy
      - magnetdb
    cap_add:
      - NET_ADMIN
    privileged: true
    restart: always
      

  redis:
    image: redis
    container_name: redis-app
    ports:
      - 6379:6379
    environment:
      TZ: 'Europe/Paris'
      VIRTUAL_HOST: redis.lncmig.local
      NETWORK_ACCESS: internal
    depends_on:
      - nginx-proxy

  postgres:
    image: postgres:13
    container_name: postgres-app
    ports:
      - 5432:5432
    user: "${UUID}:${GID}"
    environment:
      VIRTUAL_HOST: postgres.lncmig.local
      POSTGRES_USER: magnetdb
      POSTGRES_PASSWORD: magnetdb
      TZ: 'Europe/Paris'
      PGTZ: 'Europe/Paris'
      NETWORK_ACCESS: internal
    volumes:
      - ../magnetdb-data/postgres-data:/var/lib/postgresql/data
    depends_on:
      - nginx-proxy

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-app
    environment:
      VIRTUAL_HOST: pgadmin.lncmig.local
      PGADMIN_DEFAULT_EMAIL: christophe.trophime@lncmi.cnrs.fr
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      TIMEZONE: 'Europe/Paris'
      NETWORK_ACCESS: internal
    volumes:
      - ../magnetdb-data/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - 5050:80
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: magnetdb-minio
    entrypoint: sh
    command: 
      -c 'mkdir -p /data/magnetdb && minio server /data --console-address ":9080"'
    environment:
      VIRTUAL_HOST: minio.lncmig.local
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      TZ: 'Europe/Paris'
      NETWORK_ACCESS: internal
    ports:
      - 9000:9000
      - 9080:9080
    volumes:
      - ../magnetdb-data/minio-data:/data
    depends_on:
      - nginx-proxy

  magnetdb:
    image: node:16
    container_name: magnetdb-webapp
    command:
      - /bin/bash
      - -c
      - |
        npm install -g npm@9.6.6
        mkdir -p /root/.config/yarn
        npx browserslist@latest --update-db
        yarn install
        yarn serve --public
    working_dir: /app
    volumes:
      - ./web:/app
    depends_on:
      - nginx-proxy
    environment:
      VIRTUAL_HOST: magnetdb.lncmig.local
      TZ: 'Europe/Paris'
      NETWORK_ACCESS: internal
      API_ENDPOINT: http://magnetdb-api.lncmig.local:8000
    ports:
      - 8080:8080

  magnetdb-api:
    build: .
    privileged: true
    container_name: magnetdb-api
    command: 
      - /bin/bash
      - -c
      - |
        cd python_magnetsetup
        poetry install --no-cache
        cd ..
        poetry install --no-cache
        wait-for-it magnetdb.lncmig.local:8080 -t 120 -- poetry run uvicorn python_magnetdb.web:app --host 0.0.0.0 --port 8000 --reload
    # eventually perform a migration
    working_dir: /home/feelpp/test
    network_mode: host
    volumes:
      - .:/home/feelpp/test
      - ../magnetdb-data/poetry-cache:/home/feelpp/.cache/pypoetry
      - ./images:/images
      - ./data/:/data_dir
    depends_on:
      - lemonldap-app
      - redis
      - postgres
      - minio
      - magnetdb
    environment:
      VIRTUAL_HOST: magnetdb-api.lncmig.local
      S3_ENDPOINT: minio.lncmig.local:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET: magnetdb
      DATABASE_HOST: postgres.lncmig.local
      IMAGES_DIR: /images
      TZ: 'Europe/Paris'
      NETWORK_ACCESS: internal
    ports:
      - 8000:8000

  magnetdb-worker:
    build: .
    privileged: true
    container_name: magnetdb-worker
    command:
      - /bin/bash
      - -c
      - |
        cd python_magnetsetup
        poetry install --no-cache
        cd ..
        poetry install --no-cache
        wait-for-it magnetdb-api.lncmig.local:8000 -t 120 -- watchmedo auto-restart -d ./python_magnetdb/ -p '**/*.py' --recursive -- poetry run celery -A python_magnetdb.worker worker --loglevel=info
    working_dir: /home/feelpp/test
    network_mode: host
    volumes:
      - .:/home/feelpp/test
      - ../magnetdb-data/poetry-cache-worker:/home/feelpp/.cache/pypoetry
      - ./images:/images
      - ./data/:/data_dir
    depends_on:
      - redis
      - postgres
      - minio
      - magnetdb-api
    environment:
      VIRTUAL_HOST: magnetdb-worker.lncmig.local
      S3_ENDPOINT: minio.lncmig.local:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET: magnetdb
      REDIS_ADDR: redis://redis.lncmig.local:6379/0
      DATABASE_HOST: postgres.lncmig.local
      IMAGES_DIR: /images
      TZ: 'Europe/Paris'
      NETWORK_ACCESS: internal

volumes:
  minio-data: {}
  postgres-data: {}
  pgadmin-data: {}
  lemonldap-ng-data: {}

