# Generated by Django 5.0.7 on 2024-07-23 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('nuance', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('t_ref', models.FloatField(default=20)),
                ('volumic_mass', models.FloatField(default=0)),
                ('alpha', models.FloatField(default=0)),
                ('specific_heat', models.FloatField(default=0)),
                ('electrical_conductivity', models.FloatField(default=0)),
                ('thermal_conductivity', models.FloatField(default=0)),
                ('magnet_permeability', models.FloatField(default=0)),
                ('young', models.FloatField(default=0)),
                ('poisson', models.FloatField(default=0)),
                ('expansion_coefficient', models.FloatField(default=0)),
                ('rpe', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'records',
            },
        ),
        migrations.CreateModel(
            name='StorageAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('content_type', models.CharField(max_length=255, null=True)),
                ('key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'storage_attachments',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(default='guest', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='CadAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resource_id', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnetdb.storageattachment')),
            ],
            options={
                'db_table': 'cad_attachments',
            },
        ),
        migrations.CreateModel(
            name='Magnet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design_office_reference', models.CharField(max_length=255, null=True)),
                ('cao_attachment', models.ManyToManyField(to='magnetdb.cadattachment')),
            ],
            options={
                'db_table': 'magnets',
            },
        ),
        migrations.CreateModel(
            name='MagnetPart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('commissioned_at', models.DateTimeField()),
                ('decommissioned_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('magnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnetdb.magnet')),
            ],
            options={
                'db_table': 'magnet_parts',
            },
        ),
        migrations.AddField(
            model_name='magnet',
            name='magnet_parts',
            field=models.ManyToManyField(related_name='magnet_magnet_parts', to='magnetdb.magnetpart'),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design_office_reference', models.CharField(max_length=255, null=True)),
                ('cao_attachment', models.ManyToManyField(to='magnetdb.cadattachment')),
                ('magnet_parts', models.ManyToManyField(related_name='part_magnet_parts', to='magnetdb.magnetpart')),
                ('magnets', models.ManyToManyField(through='magnetdb.MagnetPart', to='magnetdb.magnet')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnetdb.material')),
            ],
            options={
                'db_table': 'parts',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='parts',
            field=models.ManyToManyField(related_name='material_parts', to='magnetdb.part'),
        ),
        migrations.AddField(
            model_name='magnetpart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnetdb.part'),
        ),
        migrations.AddField(
            model_name='magnet',
            name='parts',
            field=models.ManyToManyField(through='magnetdb.MagnetPart', to='magnetdb.part'),
        ),
        migrations.CreateModel(
            name='PartGeometry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnetdb.part')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnetdb.storageattachment')),
            ],
            options={
                'db_table': 'part_geometries',
            },
        ),
        migrations.AddField(
            model_name='part',
            name='geometries',
            field=models.ManyToManyField(related_name='part_part_geometries', to='magnetdb.partgeometry'),
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.TextField(default='pending', null=True)),
                ('resource_id', models.BigIntegerField(null=True)),
                ('method', models.TextField(null=True)),
                ('model', models.TextField(null=True)),
                ('geometry', models.TextField(null=True)),
                ('cooling', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('static', models.BooleanField(null=True)),
                ('non_linear', models.BooleanField(null=True)),
                ('setup_status', models.TextField(default='pending')),
                ('setup_state', models.JSONField(null=True)),
                ('resource_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'simulations',
            },
        ),
        migrations.CreateModel(
            name='SimulationCurrent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('magnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnetdb.magnet')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnetdb.simulation')),
            ],
            options={
                'db_table': 'simulation_currents',
            },
        ),
        migrations.AddField(
            model_name='simulation',
            name='currents',
            field=models.ManyToManyField(related_name='simulation_simulation_currents', to='magnetdb.simulationcurrent'),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('records', models.ManyToManyField(related_name='site_records', to='magnetdb.record')),
            ],
            options={
                'db_table': 'sites',
            },
        ),
        migrations.AddField(
            model_name='record',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnetdb.site'),
        ),
        migrations.CreateModel(
            name='SiteMagnet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('commissioned_at', models.DateTimeField()),
                ('decommissioned_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('magnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnetdb.magnet')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnetdb.site')),
            ],
            options={
                'db_table': 'site_magnets',
            },
        ),
        migrations.AddField(
            model_name='site',
            name='magnets',
            field=models.ManyToManyField(through='magnetdb.SiteMagnet', to='magnetdb.magnet'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_magnets',
            field=models.ManyToManyField(related_name='site_site_magnets', to='magnetdb.sitemagnet'),
        ),
        migrations.AddField(
            model_name='magnet',
            name='site_magnets',
            field=models.ManyToManyField(related_name='magnet_site_magnets', to='magnetdb.sitemagnet'),
        ),
        migrations.AddField(
            model_name='magnet',
            name='sites',
            field=models.ManyToManyField(through='magnetdb.SiteMagnet', to='magnetdb.site'),
        ),
        migrations.AddField(
            model_name='site',
            name='config_attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magnetdb.storageattachment'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='log_attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_log_attachment', to='magnetdb.storageattachment'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='output_attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_output_attachment', to='magnetdb.storageattachment'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='setup_output_attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_setup_output_attachment', to='magnetdb.storageattachment'),
        ),
        migrations.AddField(
            model_name='record',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnetdb.storageattachment'),
        ),
        migrations.AddField(
            model_name='magnet',
            name='geometry_attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magnetdb.storageattachment'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magnetdb.user'),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_directory', models.CharField(max_length=255)),
                ('type', models.CharField(default='compute', max_length=255)),
                ('smp', models.BooleanField(default=True)),
                ('multithreading', models.BooleanField(default=True)),
                ('cores', models.IntegerField(default=1)),
                ('dns', models.CharField(default='localhost', max_length=255)),
                ('job_manager', models.CharField(default='none', max_length=255)),
                ('mesh_gems_directory', models.CharField(default='/opt/MeshGems', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnetdb.user')),
            ],
            options={
                'db_table': 'servers',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(null=True)),
                ('resource_id', models.BigIntegerField(null=True)),
                ('resource_name', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnetdb.user')),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
    ]
