
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='python_magnetapi',
    version='0.1.0',
    python_requires='==3.*,>=3.8.0',
    author='Christophe Trophime',
    author_email='christophe.trophime@lncmi.cnrs.fr',
    maintainer='Remi Caumette',
    maintainer_email='remicaumette@icloud.com',
    packages=[],
    package_dir={"": "."},
    package_data={},
    install_requires=['numpy==1.*,>=1.22.3', 'pandas==1.*,>=1.4.1', 'param==1.*,>=1.12.0', 'requests==2.*,>=2.27.1', 'rich==9.*,>=9.11.0', 'scipy==1.*,>=1.22.3',
                      'python-magnettools', 'python-magnetrun'],
)
