# Generated by Django 5.0.7 on 2024-07-24 09:50

import jsonfield.fields
from django.db import migrations, IntegrityError, transaction


def convert_resource(apps, schema_editor):
    Simulation = apps.get_model("magnetdb", "Simulation")
    for simulation in Simulation.objects.all():
        try:
            with transaction.atomic():
                if simulation.resource_type == 'magnets':
                    simulation.magnet_id = simulation.resource_id
                    simulation.save()
                if simulation.resource_type == 'sites':
                    simulation.site_id = simulation.resource_id
                    simulation.save()
        except IntegrityError:
            simulation.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('magnetdb', '0003_remove_cadattachment_resource_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='setup_state',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.RunPython(convert_resource, reverse_code=migrations.RunPython.noop),
    ]
