from orator.seeds import Seeder


class MaterialTableSeeder(Seeder):
    def run(self):
        self.db.table('materials').insert([
            {
                'name': 'MA15101601',
                'description': 'H1',
                'nuance': 'CuAg5.5',
                't_ref': 293,
                'volumic_mass': 9e+3,
                'specific_heat': 0,
                'alpha': 3.6e-3,
                'electrical_conductivity': 52.4e+6,
                'thermal_conductivity': 380,
                'magnet_permeability': 1,
                'young': 117e+9,
                'poisson': 0.33,
                'expansion_coefficient': 18e-6,
                'rpe': 481,
            },
            {
                'name': 'MA15061703',
                'description': 'H2',
                'nuance': 'CuAg5.5',
                't_ref': 293,
                'volumic_mass': 9e+3,
                'specific_heat': 0,
                'alpha': 3.6e-3,
                'electrical_conductivity': 53.3e+6,
                'thermal_conductivity': 380,
                'magnet_permeability': 1,
                'young': 117e+9,
                'poisson': 0.33,
                'expansion_coefficient': 18e-6,
                'rpe': 482,
            },
            {
                'name': 'MA15061801',
                'description': 'H3',
                'nuance': 'CuAg5.5',
                't_ref': 293,
                'volumic_mass': 9e+3,
                'specific_heat': 0,
                'alpha': 3.6e-3,
                'electrical_conductivity': 52.6e+6,
                'thermal_conductivity': 380,
                'magnet_permeability': 1,
                'young': 117e+9,
                'poisson': 0.33,
                'expansion_coefficient': 18e-6,
                'rpe': 496,
            },
            {
                'name': 'MA15100501',
                'description': 'H4',
                'nuance': 'CuAg5.5',
                't_ref': 293,
                'volumic_mass': 9e+3,
                'specific_heat': 0,
                'alpha': 3.6e-3,
                'electrical_conductivity': 52.8e+6,
                'thermal_conductivity': 380,
                'magnet_permeability': 1,
                'young': 117e+9,
                'poisson': 0.33,
                'expansion_coefficient': 18e-6,
                'rpe': 508,
            },
            {
                'name': 'MA15101501',
                'description': 'H5',
                'nuance': 'CuAg5.5',
                't_ref': 293,
                'volumic_mass': 9e+3,
                'specific_heat': 0,
                'alpha': 3.6e-3,
                'electrical_conductivity': 53.1e+6,
                'thermal_conductivity': 380,
                'magnet_permeability': 1,
                'young': 117e+9,
                'poisson': 0.33,
                'expansion_coefficient': 18e-6,
                'rpe': 506,
            },
            {
                'name': 'MA18060101',
                'description': 'H6',
                'nuance': 'CuAg5.5',
                't_ref': 293,
                'volumic_mass': 9e+3,
                'specific_heat': 0,
                'alpha': 3.6e-3,
                'electrical_conductivity': 53.2e+6,
                'thermal_conductivity': 380,
                'magnet_permeability': 1,
                'young': 117e+9,
                'poisson': 0.33,
                'expansion_coefficient': 18e-6,
                'rpe': 512,
            },
            {
                'name': 'MA18012501',
                'description': 'H7',
                'nuance': 'CuAg5.5',
                't_ref': 293,
                'volumic_mass': 9e+3,
                'specific_heat': 0,
                'alpha': 3.6e-3,
                'electrical_conductivity': 53.1e+6,
                'thermal_conductivity': 380,
                'magnet_permeability': 1,
                'young': 117e+9,
                'poisson': 0.33,
                'expansion_coefficient': 18e-6,
                'rpe': 500,
            },
            {
                'name': 'MA18051801',
                'description': 'H8',
                'nuance': 'CuAg5.5',
                't_ref': 293,
                'volumic_mass': 9e+3,
                'specific_heat': 0,
                'alpha': 3.6e-3,
                'electrical_conductivity': 51.9e+6,
                'thermal_conductivity': 380,
                'magnet_permeability': 1,
                'young': 117e+9,
                'poisson': 0.33,
                'expansion_coefficient': 18e-6,
                'rpe': 512,
            },
            {
                'name': 'MA18101201',
                'description': 'H9',
                'nuance': 'CuAg5.5',
                't_ref': 293,
                'volumic_mass': 9e+3,
                'specific_heat': 0,
                'alpha': 3.6e-3,
                'electrical_conductivity': 53.7e+6,
                'thermal_conductivity': 380,
                'magnet_permeability': 1,
                'young': 117e+9,
                'poisson': 0.33,
                'expansion_coefficient': 18e-6,
                'rpe': 500,
            },
            {
                'name': 'MA18101201',
                'description': 'H10',
                'nuance': 'CuAg5.5',
                't_ref': 293,
                'volumic_mass': 9e+3,
                'specific_heat': 0,
                'alpha': 3.6e-3,
                'electrical_conductivity': 53.3e+6,
                'thermal_conductivity': 380,
                'magnet_permeability': 1,
                'young': 117e+9,
                'poisson': 0.33,
                'expansion_coefficient': 18e-6,
                'rpe': 500,
            },
            {
                'name': 'MA19012101',
                'description': 'H11',
                'nuance': 'CuAg5.5',
                't_ref': 293,
                'volumic_mass': 9e+3,
                'specific_heat': 0,
                'alpha': 3.6e-3,
                'electrical_conductivity': 53.8e+6,
                'thermal_conductivity': 380,
                'magnet_permeability': 1,
                'young': 117e+9,
                'poisson': 0.33,
                'expansion_coefficient': 18e-6,
                'rpe': 500,
            },
            {
                'name': 'MA19011601',
                'description': 'H12',
                'nuance': 'CuAg5.5',
                't_ref': 293,
                'volumic_mass': 9e+3,
                'specific_heat': 0,
                'alpha': 3.6e-3,
                'electrical_conductivity': 53.2e+6,
                'thermal_conductivity': 380,
                'magnet_permeability': 1,
                'young': 117e+9,
                'poisson': 0.33,
                'expansion_coefficient': 18e-6,
                'rpe': 500,
            },
            {
                'name': 'MA10061702',
                'description': 'H13',
                'nuance': 'CuCrZr',
                't_ref': 293,
                'volumic_mass': 9e+3,
                'specific_heat': 0,
                'alpha': 3.4e-3,
                'electrical_conductivity': 46.5e+6,
                'thermal_conductivity': 380,
                'magnet_permeability': 1,
                'young': 117e+9,
                'poisson': 0.33,
                'expansion_coefficient': 18e-6,
                'rpe': 366,
            },
            {
                'name': 'MA10061703',
                'description': 'H14',
                'nuance': 'CuCrZr',
                't_ref': 293,
                'volumic_mass': 9e+3,
                'specific_heat': 0,
                'alpha': 3.4e-3,
                'electrical_conductivity': 50.25e+6,
                'thermal_conductivity': 380,
                'magnet_permeability': 1,
                'young': 117e+9,
                'poisson': 0.33,
                'expansion_coefficient': 18e-6,
                'rpe': 373,
            },
            {
                'name': 'MAT1_RING',
                'description': 'R1, R2',
                'nuance': 'unknow',
                't_ref': 293,
                'volumic_mass': 9e+3,
                'specific_heat': 0,
                'alpha': 3.4e-3,
                'electrical_conductivity': 41e+6,
                'thermal_conductivity': 320,
                'magnet_permeability': 1,
                'young': 131e+9,
                'poisson': 0.3,
                'expansion_coefficient': 17e-6,
                'rpe': 0,
            },
            {
                'name': 'MAT2_RING',
                'description': 'R3, R4, R5, R6, R7, R8, R9, R10, R11, R12, R13',
                'nuance': 'unknow',
                't_ref': 293,
                'volumic_mass': 9e+3,
                'specific_heat': 0,
                'alpha': 3.4e-3,
                'electrical_conductivity': 50e+6,
                'thermal_conductivity': 320,
                'magnet_permeability': 1,
                'young': 131e+9,
                'poisson': 0.3,
                'expansion_coefficient': 17e-6,
                'rpe': 0,
            },
            {
                'name': 'MAT_LEAD',
                'description': 'il1 ol2',
                'nuance': 'unknow',
                't_ref': 293,
                'volumic_mass': 9e+3,
                'specific_heat': 0,
                'alpha': 3.4e-3,
                'electrical_conductivity': 58.0e+6,
                'thermal_conductivity': 390,
                'magnet_permeability': 1,
                'young': 131e+9,
                'poisson': 0.3,
                'expansion_coefficient': 17e-6,
                'rpe': 0,
            },
            {
                'name': 'MAT_ISOLANT',
                'description': None,
                'nuance': 'unknow',
                't_ref': 20,
                'volumic_mass': 2e+3,
                'specific_heat': 0,
                'alpha': 0,
                'electrical_conductivity': 0,
                'thermal_conductivity': 1.2,
                'magnet_permeability': 1,
                'young': 2.1e9,
                'poisson': 0.21,
                'expansion_coefficient': 9e-6,
                'rpe': 0,
            },
        ])
