"""
Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from os import getenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = 'django-insecure-rlqo26vtu_ual+%d70%woq68&f)165m!#v)d*lk9-!%dl&3j6v'

DEBUG = True

INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'python_magnetdb',
]

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.postgresql",
        'HOST': getenv('DATABASE_HOST') or 'localhost',
        'NAME': getenv('DATABASE_NAME') or 'magnetdb',
        'USER': getenv('DATABASE_USER') or 'magnetdb',
        'PASSWORD': getenv('DATABASE_PASSWORD') or 'magnetdb',
    }
}


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
