tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/ssl/traefik/magnetdb-dev.local.pem
        keyFile: /etc/ssl/traefik/magnetdb-dev.local-key.pem
  certificates:
    - certFile: /etc/ssl/traefik/_wildcard.magnetdb-dev.local.pem
      keyFile: /etc/ssl/traefik/_wildcard.magnetdb-dev.local-key.pem
